---
title: "Dashboard for Instacart Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r load and manipulate, include=FALSE}
data("instacart")

dow_df = 
  tibble(
    order_dow = c(0:6),
    day_of_week = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
  )

instacart = 
  instacart %>% 
  left_join(dow_df, by = "order_dow")
```


### Number of orders by hour for each day of the week

```{r}
order_by_hour = 
  instacart %>% 
  group_by(order_dow, day_of_week, order_hour_of_day) %>% 
  summarize(order_count = n_distinct(order_id)) %>% 
  mutate(
    day_of_week = fct_reorder(day_of_week, order_dow),
    text_label = str_c("Hour of the day: ", order_hour_of_day, "\nNumber of orders: ", order_count)
  ) %>% 
  plot_ly(
    y = ~order_count, x = ~order_hour_of_day, color = ~day_of_week,
    type = "scatter", mode = "markers+lines", colors = "viridis", text = ~text_label, alpha = .5
    ) %>% 
  layout(
    title = "Number of orders made in each hour of the day for each day of the week",
    xaxis = list(title = "Hour of the day"),
    yaxis = list(title = "Number of orders")
  )

order_by_hour
```


### Number of items by top 10 department

```{r}
item_by_department = 
  instacart %>% 
  count(department) %>% 
  mutate(
    dep_rank = min_rank(desc(n)),
    department = fct_reorder(department, n),
    text_label = str_c("Department: ", department, "\nNumber of items ordered: ", n)
  ) %>% 
  filter(dep_rank <= 10) %>% 
  plot_ly(
    y = ~n, x = ~department, color = ~department,
    type = "bar", colors = "viridis", text = ~text_label
  ) %>% 
  layout(
    title = "Number of items ordered from each top 10 department with most items sold (1-10 from the right)",
    xaxis = list(title = "Department"),
    yaxis = list(title = "Number of items")
  )

item_by_department
```


### Ordered hour distribution for each top 10 item

```{r}
top_10_items = 
  instacart %>% 
  count(product_name) %>% 
  mutate(item_rank = min_rank(desc(n))) %>% 
  filter(item_rank <= 10)

hour_by_top_item = 
  instacart %>% 
  inner_join(top_10_items, by = "product_name") %>% 
  mutate(product_name = fct_reorder(product_name, item_rank)) %>% 
  plot_ly(
    y = ~order_hour_of_day, x = ~product_name, color = ~product_name,
    type = "box", colors = "viridis"
  ) %>% 
  layout(
    title = "Distribution of the ordered hour of the day for each top 10 best-selling item (1-10 from the left)",
    xaxis = list(title = list(text = "Product name", standoff = 2)),
    yaxis = list(title = "Ordered hour of the day")
  )

hour_by_top_item
```

